AllCops:
  NewCops: disable

  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
